### ISSUE TITLE
Proposal to move django-downloadview to JazzBand.

### ISSUE THREAD

**Issue by Natim** [jazzband/django-downloadview#154]
- [x] Add Jazzband a badge in the readme
- [x] Make sure there is a CONTRIBUTING documentation
- [x] Add the contributing JazzBand header

Full guidelines: https://jazzband.co/about/guidelines

- [ ] Open an issue to ask roadies to configure a travis rule for deployment to pypi.

**Comment by benoitbryon** [comment]
I'm ok to transfer ownership of django-downloadview to another account. I'm quite happy someone asks for it: since I've been inactive as a developer for ~4 years, new ownership is good news for the project.
And I'm glad and trustful because it's you @Natim ;)

**Comment by Natim** [comment]
> Basically all you have to do is, join Jazzband on https://jazzband.co/join (that adds you as a member to the Jazzband GitHub organization) and transfer the repo to the Jazzband GitHub organization using the standard transfer workflow.
>
> Once the repo has been transfered a new ticket is created with a TODO list to get the repo inline with the Jazzband guidelines.

I guess we are ready @benoitbryon !

**Comment by Natim** [comment]
I created https://github.com/benoitbryon/django-downloadview/pull/158 to handle this first todo.
