### ISSUE TITLE
Demo project has settings for end of life Django versions

### ISSUE THREAD

**Issue by johnthagen** [jazzband/django-downloadview#168]
The following code has settings shim for Django <= 1.9, which is end of life.

https://github.com/jazzband/django-downloadview/blob/9f42e6598618e10ad0f452fb91d7650373da8d7b/demo/demoproject/settings.py#L64-L80

This somewhat complicates the documentation which reference this:

https://django-downloadview.readthedocs.io/en/latest/settings.html#middleware-classes

For new users, dropping unsupported Django versions would make this simpler for new users.

**Comment by Natim** [comment]
Thank you for pointing this out @johnthagen . Would you be willing to file a PR about this? I would be happy to review and merge it.
