### ISSUE TITLE
Support Django 4.0

### ISSUE THREAD

**Issue by PeterTillema** [jazzband/django-downloadview#187]
`force_text` got removed from `django.utils.encoding` as used here: https://github.com/jazzband/django-downloadview/blob/0578729a66e0843bd34cf9253c81076f3b976408/django_downloadview/io.py#L4

See the release notes: https://docs.djangoproject.com/en/4.0/releases/4.0/#features-removed-in-4-0

**Comment by tari** [comment]
`force_text` was a legacy alias for `force_str` which was mostly useful for Python 2 compatibility; since this package does not support Python 2, replacing `force_text` with `force_str` should be all that's needed.

**Comment by tari** [comment]
Thanks for merging, @Natim; can there also be a new version published to PyPI?
